title: Welcome to Roslyn's Homepage
name: Sun Yaqi
name_zh: 孙雅琪
affiliation: Nanjing University
page-top-title: 孙雅琪
top-section-bg-text: Be what you wanna be
copyright-text: '© 2026 Sun Yaqi. All rights reserved.'
